name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS v14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Build
        run: npm run build
      
